// Liar games — bilingual word pools.
//
// Words are CONTENT, not UI strings, so they live here as data rather than in
// the i18n dict. Each word carries { ko, en }; the client renders the word in
// ITS OWN language (a Korean viewer and an English viewer in the same room each
// read their language), mirroring how King Game handles mission text.
//
// The server NEVER sends a resolved word string. It sends a category id + a word
// INDEX (via the private state's card), and each client looks the word up here.
// Category names themselves ARE UI strings — those live in i18n as `liarcat.*`.

export type LiarWord = { ko: string; en: string };

export type LiarCategoryId =
  | "countries"
  | "fruits"
  | "vegetables"
  | "animals"
  | "jobs"
  | "sports"
  | "furniture"
  | "brands"
  | "insects";

export const LIAR_CATEGORY_IDS: LiarCategoryId[] = [
  "countries",
  "fruits",
  "vegetables",
  "animals",
  "jobs",
  "sports",
  "furniture",
  "brands",
  "insects",
];

export const LIAR_CATEGORIES: Record<LiarCategoryId, LiarWord[]> = {
  countries: [
    { ko: "대한민국", en: "South Korea" },
    { ko: "일본", en: "Japan" },
    { ko: "중국", en: "China" },
    { ko: "미국", en: "United States" },
    { ko: "영국", en: "United Kingdom" },
    { ko: "프랑스", en: "France" },
    { ko: "독일", en: "Germany" },
    { ko: "이탈리아", en: "Italy" },
    { ko: "스페인", en: "Spain" },
    { ko: "캐나다", en: "Canada" },
    { ko: "호주", en: "Australia" },
    { ko: "브라질", en: "Brazil" },
    { ko: "아르헨티나", en: "Argentina" },
    { ko: "멕시코", en: "Mexico" },
    { ko: "인도", en: "India" },
    { ko: "러시아", en: "Russia" },
    { ko: "베트남", en: "Vietnam" },
    { ko: "태국", en: "Thailand" },
    { ko: "인도네시아", en: "Indonesia" },
    { ko: "필리핀", en: "Philippines" },
    { ko: "말레이시아", en: "Malaysia" },
    { ko: "싱가포르", en: "Singapore" },
    { ko: "네덜란드", en: "Netherlands" },
    { ko: "스위스", en: "Switzerland" },
    { ko: "스웨덴", en: "Sweden" },
    { ko: "노르웨이", en: "Norway" },
    { ko: "핀란드", en: "Finland" },
    { ko: "덴마크", en: "Denmark" },
    { ko: "그리스", en: "Greece" },
    { ko: "튀르키예", en: "Turkey" },
    { ko: "이집트", en: "Egypt" },
    { ko: "남아프리카공화국", en: "South Africa" },
    { ko: "케냐", en: "Kenya" },
    { ko: "나이지리아", en: "Nigeria" },
    { ko: "사우디아라비아", en: "Saudi Arabia" },
    { ko: "아랍에미리트", en: "United Arab Emirates" },
    { ko: "이스라엘", en: "Israel" },
    { ko: "포르투갈", en: "Portugal" },
    { ko: "폴란드", en: "Poland" },
    { ko: "오스트리아", en: "Austria" },
    { ko: "벨기에", en: "Belgium" },
    { ko: "아일랜드", en: "Ireland" },
    { ko: "뉴질랜드", en: "New Zealand" },
    { ko: "칠레", en: "Chile" },
    { ko: "페루", en: "Peru" },
    { ko: "콜롬비아", en: "Colombia" },
    { ko: "쿠바", en: "Cuba" },
    { ko: "몽골", en: "Mongolia" },
    { ko: "네팔", en: "Nepal" },
    { ko: "아이슬란드", en: "Iceland" },
  ],
  fruits: [
    { ko: "사과", en: "Apple" },
    { ko: "배", en: "Pear" },
    { ko: "포도", en: "Grape" },
    { ko: "딸기", en: "Strawberry" },
    { ko: "바나나", en: "Banana" },
    { ko: "오렌지", en: "Orange" },
    { ko: "귤", en: "Tangerine" },
    { ko: "수박", en: "Watermelon" },
    { ko: "참외", en: "Korean melon" },
    { ko: "멜론", en: "Melon" },
    { ko: "복숭아", en: "Peach" },
    { ko: "자두", en: "Plum" },
    { ko: "체리", en: "Cherry" },
    { ko: "키위", en: "Kiwi" },
    { ko: "파인애플", en: "Pineapple" },
    { ko: "망고", en: "Mango" },
    { ko: "레몬", en: "Lemon" },
    { ko: "라임", en: "Lime" },
    { ko: "자몽", en: "Grapefruit" },
    { ko: "블루베리", en: "Blueberry" },
    { ko: "라즈베리", en: "Raspberry" },
    { ko: "무화과", en: "Fig" },
    { ko: "감", en: "Persimmon" },
    { ko: "석류", en: "Pomegranate" },
    { ko: "살구", en: "Apricot" },
    { ko: "망고스틴", en: "Mangosteen" },
    { ko: "두리안", en: "Durian" },
    { ko: "리치", en: "Lychee" },
    { ko: "코코넛", en: "Coconut" },
    { ko: "파파야", en: "Papaya" },
    { ko: "패션프루트", en: "Passion fruit" },
    { ko: "크랜베리", en: "Cranberry" },
    { ko: "블랙베리", en: "Blackberry" },
    { ko: "대추", en: "Jujube" },
    { ko: "모과", en: "Quince" },
    { ko: "앵두", en: "Cornelian cherry" },
    { ko: "매실", en: "Green plum" },
    { ko: "천도복숭아", en: "Nectarine" },
    { ko: "아보카도", en: "Avocado" },
    { ko: "구아바", en: "Guava" },
    { ko: "람부탄", en: "Rambutan" },
    { ko: "용과", en: "Dragon fruit" },
    { ko: "청포도", en: "Green grape" },
    { ko: "거봉", en: "Kyoho grape" },
    { ko: "한라봉", en: "Hallabong" },
    { ko: "금귤", en: "Kumquat" },
    { ko: "블랙커런트", en: "Blackcurrant" },
    { ko: "구스베리", en: "Gooseberry" },
    { ko: "대추야자", en: "Date" },
    { ko: "스타프루트", en: "Star fruit" },
  ],
  vegetables: [
    { ko: "배추", en: "Napa cabbage" },
    { ko: "양배추", en: "Cabbage" },
    { ko: "무", en: "Radish" },
    { ko: "당근", en: "Carrot" },
    { ko: "양파", en: "Onion" },
    { ko: "대파", en: "Green onion" },
    { ko: "마늘", en: "Garlic" },
    { ko: "생강", en: "Ginger" },
    { ko: "감자", en: "Potato" },
    { ko: "고구마", en: "Sweet potato" },
    { ko: "오이", en: "Cucumber" },
    { ko: "호박", en: "Pumpkin" },
    { ko: "애호박", en: "Zucchini" },
    { ko: "가지", en: "Eggplant" },
    { ko: "토마토", en: "Tomato" },
    { ko: "고추", en: "Chili pepper" },
    { ko: "피망", en: "Green pepper" },
    { ko: "파프리카", en: "Bell pepper" },
    { ko: "시금치", en: "Spinach" },
    { ko: "상추", en: "Lettuce" },
    { ko: "깻잎", en: "Perilla leaf" },
    { ko: "부추", en: "Chive" },
    { ko: "미나리", en: "Water parsley" },
    { ko: "쑥갓", en: "Crown daisy" },
    { ko: "콩나물", en: "Bean sprout" },
    { ko: "브로콜리", en: "Broccoli" },
    { ko: "콜리플라워", en: "Cauliflower" },
    { ko: "셀러리", en: "Celery" },
    { ko: "아스파라거스", en: "Asparagus" },
    { ko: "버섯", en: "Mushroom" },
    { ko: "표고버섯", en: "Shiitake" },
    { ko: "팽이버섯", en: "Enoki mushroom" },
    { ko: "옥수수", en: "Corn" },
    { ko: "완두콩", en: "Pea" },
    { ko: "강낭콩", en: "Kidney bean" },
    { ko: "연근", en: "Lotus root" },
    { ko: "우엉", en: "Burdock" },
    { ko: "도라지", en: "Bellflower root" },
    { ko: "더덕", en: "Deodeok" },
    { ko: "마", en: "Yam" },
    { ko: "토란", en: "Taro" },
    { ko: "비트", en: "Beet" },
    { ko: "순무", en: "Turnip" },
    { ko: "케일", en: "Kale" },
    { ko: "청경채", en: "Bok choy" },
    { ko: "양상추", en: "Iceberg lettuce" },
    { ko: "고수", en: "Cilantro" },
    { ko: "죽순", en: "Bamboo shoot" },
    { ko: "단호박", en: "Sweet pumpkin" },
    { ko: "열무", en: "Young radish" },
  ],
  animals: [
    { ko: "사자", en: "Lion" },
    { ko: "호랑이", en: "Tiger" },
    { ko: "곰", en: "Bear" },
    { ko: "코끼리", en: "Elephant" },
    { ko: "기린", en: "Giraffe" },
    { ko: "얼룩말", en: "Zebra" },
    { ko: "사슴", en: "Deer" },
    { ko: "늑대", en: "Wolf" },
    { ko: "여우", en: "Fox" },
    { ko: "토끼", en: "Rabbit" },
    { ko: "다람쥐", en: "Squirrel" },
    { ko: "너구리", en: "Raccoon dog" },
    { ko: "고양이", en: "Cat" },
    { ko: "개", en: "Dog" },
    { ko: "말", en: "Horse" },
    { ko: "소", en: "Cow" },
    { ko: "돼지", en: "Pig" },
    { ko: "양", en: "Sheep" },
    { ko: "염소", en: "Goat" },
    { ko: "닭", en: "Chicken" },
    { ko: "오리", en: "Duck" },
    { ko: "거위", en: "Goose" },
    { ko: "코뿔소", en: "Rhinoceros" },
    { ko: "하마", en: "Hippopotamus" },
    { ko: "캥거루", en: "Kangaroo" },
    { ko: "코알라", en: "Koala" },
    { ko: "판다", en: "Panda" },
    { ko: "원숭이", en: "Monkey" },
    { ko: "고릴라", en: "Gorilla" },
    { ko: "침팬지", en: "Chimpanzee" },
    { ko: "낙타", en: "Camel" },
    { ko: "표범", en: "Leopard" },
    { ko: "치타", en: "Cheetah" },
    { ko: "재규어", en: "Jaguar" },
    { ko: "북극곰", en: "Polar bear" },
    { ko: "펭귄", en: "Penguin" },
    { ko: "돌고래", en: "Dolphin" },
    { ko: "고래", en: "Whale" },
    { ko: "상어", en: "Shark" },
    { ko: "문어", en: "Octopus" },
    { ko: "거북이", en: "Turtle" },
    { ko: "악어", en: "Crocodile" },
    { ko: "뱀", en: "Snake" },
    { ko: "개구리", en: "Frog" },
    { ko: "독수리", en: "Eagle" },
    { ko: "부엉이", en: "Owl" },
    { ko: "박쥐", en: "Bat" },
    { ko: "고슴도치", en: "Hedgehog" },
    { ko: "수달", en: "Otter" },
    { ko: "두더지", en: "Mole" },
  ],
  jobs: [
    { ko: "의사", en: "Doctor" },
    { ko: "간호사", en: "Nurse" },
    { ko: "교사", en: "Teacher" },
    { ko: "교수", en: "Professor" },
    { ko: "변호사", en: "Lawyer" },
    { ko: "판사", en: "Judge" },
    { ko: "검사", en: "Prosecutor" },
    { ko: "경찰관", en: "Police officer" },
    { ko: "소방관", en: "Firefighter" },
    { ko: "군인", en: "Soldier" },
    { ko: "요리사", en: "Chef" },
    { ko: "제빵사", en: "Baker" },
    { ko: "바리스타", en: "Barista" },
    { ko: "농부", en: "Farmer" },
    { ko: "어부", en: "Fisherman" },
    { ko: "목수", en: "Carpenter" },
    { ko: "배관공", en: "Plumber" },
    { ko: "전기기사", en: "Electrician" },
    { ko: "건축가", en: "Architect" },
    { ko: "엔지니어", en: "Engineer" },
    { ko: "프로그래머", en: "Programmer" },
    { ko: "디자이너", en: "Designer" },
    { ko: "화가", en: "Painter" },
    { ko: "음악가", en: "Musician" },
    { ko: "가수", en: "Singer" },
    { ko: "배우", en: "Actor" },
    { ko: "감독", en: "Director" },
    { ko: "작가", en: "Writer" },
    { ko: "기자", en: "Journalist" },
    { ko: "아나운서", en: "Announcer" },
    { ko: "운동선수", en: "Athlete" },
    { ko: "조종사", en: "Pilot" },
    { ko: "승무원", en: "Flight attendant" },
    { ko: "운전기사", en: "Driver" },
    { ko: "택시기사", en: "Taxi driver" },
    { ko: "약사", en: "Pharmacist" },
    { ko: "수의사", en: "Veterinarian" },
    { ko: "치과의사", en: "Dentist" },
    { ko: "회계사", en: "Accountant" },
    { ko: "은행원", en: "Banker" },
    { ko: "사업가", en: "Businessperson" },
    { ko: "정치인", en: "Politician" },
    { ko: "외교관", en: "Diplomat" },
    { ko: "과학자", en: "Scientist" },
    { ko: "우주비행사", en: "Astronaut" },
    { ko: "사진작가", en: "Photographer" },
    { ko: "미용사", en: "Hairdresser" },
    { ko: "재단사", en: "Tailor" },
    { ko: "사서", en: "Librarian" },
    { ko: "통역사", en: "Interpreter" },
  ],
  sports: [
    { ko: "축구", en: "Soccer" },
    { ko: "야구", en: "Baseball" },
    { ko: "농구", en: "Basketball" },
    { ko: "배구", en: "Volleyball" },
    { ko: "테니스", en: "Tennis" },
    { ko: "탁구", en: "Table tennis" },
    { ko: "배드민턴", en: "Badminton" },
    { ko: "골프", en: "Golf" },
    { ko: "수영", en: "Swimming" },
    { ko: "다이빙", en: "Diving" },
    { ko: "육상", en: "Athletics" },
    { ko: "마라톤", en: "Marathon" },
    { ko: "권투", en: "Boxing" },
    { ko: "태권도", en: "Taekwondo" },
    { ko: "유도", en: "Judo" },
    { ko: "레슬링", en: "Wrestling" },
    { ko: "펜싱", en: "Fencing" },
    { ko: "양궁", en: "Archery" },
    { ko: "사격", en: "Shooting" },
    { ko: "체조", en: "Gymnastics" },
    { ko: "역도", en: "Weightlifting" },
    { ko: "스키", en: "Skiing" },
    { ko: "스노보드", en: "Snowboarding" },
    { ko: "스케이트", en: "Skating" },
    { ko: "피겨스케이팅", en: "Figure skating" },
    { ko: "아이스하키", en: "Ice hockey" },
    { ko: "컬링", en: "Curling" },
    { ko: "봅슬레이", en: "Bobsleigh" },
    { ko: "사이클", en: "Cycling" },
    { ko: "승마", en: "Horse riding" },
    { ko: "조정", en: "Rowing" },
    { ko: "카누", en: "Canoeing" },
    { ko: "서핑", en: "Surfing" },
    { ko: "요트", en: "Sailing" },
    { ko: "클라이밍", en: "Climbing" },
    { ko: "핸드볼", en: "Handball" },
    { ko: "럭비", en: "Rugby" },
    { ko: "미식축구", en: "American football" },
    { ko: "크리켓", en: "Cricket" },
    { ko: "하키", en: "Field hockey" },
    { ko: "당구", en: "Billiards" },
    { ko: "볼링", en: "Bowling" },
    { ko: "스쿼시", en: "Squash" },
    { ko: "카약", en: "Kayaking" },
    { ko: "철인3종", en: "Triathlon" },
    { ko: "스카이다이빙", en: "Skydiving" },
    { ko: "패러글라이딩", en: "Paragliding" },
    { ko: "스케이트보드", en: "Skateboarding" },
    { ko: "비치발리볼", en: "Beach volleyball" },
    { ko: "이스포츠", en: "Esports" },
  ],
  furniture: [
    { ko: "침대", en: "Bed" },
    { ko: "소파", en: "Sofa" },
    { ko: "의자", en: "Chair" },
    { ko: "책상", en: "Desk" },
    { ko: "식탁", en: "Dining table" },
    { ko: "탁자", en: "Table" },
    { ko: "옷장", en: "Wardrobe" },
    { ko: "서랍장", en: "Drawer chest" },
    { ko: "책장", en: "Bookshelf" },
    { ko: "신발장", en: "Shoe cabinet" },
    { ko: "화장대", en: "Dressing table" },
    { ko: "거울", en: "Mirror" },
    { ko: "식기장", en: "Cupboard" },
    { ko: "찬장", en: "Cabinet" },
    { ko: "선반", en: "Shelf" },
    { ko: "협탁", en: "Nightstand" },
    { ko: "스툴", en: "Stool" },
    { ko: "벤치", en: "Bench" },
    { ko: "안락의자", en: "Armchair" },
    { ko: "흔들의자", en: "Rocking chair" },
    { ko: "소파베드", en: "Sofa bed" },
    { ko: "이층침대", en: "Bunk bed" },
    { ko: "옷걸이", en: "Coat rack" },
    { ko: "행거", en: "Clothes rack" },
    { ko: "수납장", en: "Storage cabinet" },
    { ko: "티비장", en: "TV stand" },
    { ko: "콘솔", en: "Console table" },
    { ko: "화이트보드", en: "Whiteboard" },
    { ko: "칸막이", en: "Partition" },
    { ko: "파티션", en: "Divider" },
    { ko: "책꽂이", en: "Book stand" },
    { ko: "매트리스", en: "Mattress" },
    { ko: "러그", en: "Rug" },
    { ko: "카펫", en: "Carpet" },
    { ko: "커튼", en: "Curtain" },
    { ko: "블라인드", en: "Blind" },
    { ko: "조명", en: "Lamp" },
    { ko: "스탠드", en: "Floor lamp" },
    { ko: "캐비닛", en: "File cabinet" },
    { ko: "사물함", en: "Locker" },
    { ko: "평상", en: "Wooden platform" },
    { ko: "좌식테이블", en: "Floor table" },
    { ko: "빈백", en: "Bean bag" },
    { ko: "해먹", en: "Hammock" },
    { ko: "와인랙", en: "Wine rack" },
    { ko: "우산꽂이", en: "Umbrella stand" },
    { ko: "화분받침", en: "Plant stand" },
    { ko: "거실장", en: "Living room cabinet" },
    { ko: "침실등", en: "Bedside lamp" },
    { ko: "장식장", en: "Display cabinet" },
  ],
  brands: [
    { ko: "삼성", en: "Samsung" },
    { ko: "애플", en: "Apple" },
    { ko: "엘지", en: "LG" },
    { ko: "현대", en: "Hyundai" },
    { ko: "기아", en: "Kia" },
    { ko: "소니", en: "Sony" },
    { ko: "구글", en: "Google" },
    { ko: "마이크로소프트", en: "Microsoft" },
    { ko: "아마존", en: "Amazon" },
    { ko: "페이스북", en: "Facebook" },
    { ko: "인스타그램", en: "Instagram" },
    { ko: "유튜브", en: "YouTube" },
    { ko: "넷플릭스", en: "Netflix" },
    { ko: "테슬라", en: "Tesla" },
    { ko: "토요타", en: "Toyota" },
    { ko: "혼다", en: "Honda" },
    { ko: "벤츠", en: "Mercedes-Benz" },
    { ko: "비엠더블유", en: "BMW" },
    { ko: "아우디", en: "Audi" },
    { ko: "폭스바겐", en: "Volkswagen" },
    { ko: "포르쉐", en: "Porsche" },
    { ko: "페라리", en: "Ferrari" },
    { ko: "나이키", en: "Nike" },
    { ko: "아디다스", en: "Adidas" },
    { ko: "퓨마", en: "Puma" },
    { ko: "뉴발란스", en: "New Balance" },
    { ko: "구찌", en: "Gucci" },
    { ko: "샤넬", en: "Chanel" },
    { ko: "루이비통", en: "Louis Vuitton" },
    { ko: "에르메스", en: "Hermes" },
    { ko: "프라다", en: "Prada" },
    { ko: "스타벅스", en: "Starbucks" },
    { ko: "맥도날드", en: "McDonald's" },
    { ko: "코카콜라", en: "Coca-Cola" },
    { ko: "펩시", en: "Pepsi" },
    { ko: "버거킹", en: "Burger King" },
    { ko: "케이에프씨", en: "KFC" },
    { ko: "이케아", en: "IKEA" },
    { ko: "유니클로", en: "Uniqlo" },
    { ko: "자라", en: "Zara" },
    { ko: "에이치앤엠", en: "H&M" },
    { ko: "디즈니", en: "Disney" },
    { ko: "레고", en: "Lego" },
    { ko: "코스트코", en: "Costco" },
    { ko: "월마트", en: "Walmart" },
    { ko: "인텔", en: "Intel" },
    { ko: "엔비디아", en: "Nvidia" },
    { ko: "화웨이", en: "Huawei" },
    { ko: "샤오미", en: "Xiaomi" },
    { ko: "카카오", en: "Kakao" },
  ],
  insects: [
    { ko: "나비", en: "Butterfly" },
    { ko: "나방", en: "Moth" },
    { ko: "잠자리", en: "Dragonfly" },
    { ko: "벌", en: "Bee" },
    { ko: "꿀벌", en: "Honeybee" },
    { ko: "말벌", en: "Hornet" },
    { ko: "개미", en: "Ant" },
    { ko: "파리", en: "Fly" },
    { ko: "모기", en: "Mosquito" },
    { ko: "바퀴벌레", en: "Cockroach" },
    { ko: "귀뚜라미", en: "Cricket" },
    { ko: "메뚜기", en: "Grasshopper" },
    { ko: "베짱이", en: "Katydid" },
    { ko: "사마귀", en: "Mantis" },
    { ko: "무당벌레", en: "Ladybug" },
    { ko: "딱정벌레", en: "Beetle" },
    { ko: "사슴벌레", en: "Stag beetle" },
    { ko: "장수풍뎅이", en: "Rhinoceros beetle" },
    { ko: "풍뎅이", en: "Scarab beetle" },
    { ko: "매미", en: "Cicada" },
    { ko: "반딧불이", en: "Firefly" },
    { ko: "진딧물", en: "Aphid" },
    { ko: "거미", en: "Spider" },
    { ko: "전갈", en: "Scorpion" },
    { ko: "지네", en: "Centipede" },
    { ko: "노래기", en: "Millipede" },
    { ko: "진드기", en: "Tick" },
    { ko: "벼룩", en: "Flea" },
    { ko: "이", en: "Louse" },
    { ko: "빈대", en: "Bedbug" },
    { ko: "흰개미", en: "Termite" },
    { ko: "물방개", en: "Diving beetle" },
    { ko: "소금쟁이", en: "Water strider" },
    { ko: "하늘소", en: "Longhorn beetle" },
    { ko: "방아깨비", en: "Pygmy grasshopper" },
    { ko: "여치", en: "Bush cricket" },
    { ko: "굼벵이", en: "Grub" },
    { ko: "애벌레", en: "Caterpillar" },
    { ko: "번데기", en: "Pupa" },
    { ko: "누에", en: "Silkworm" },
    { ko: "쇠똥구리", en: "Dung beetle" },
    { ko: "물장군", en: "Giant water bug" },
    { ko: "가뢰", en: "Blister beetle" },
    { ko: "등에", en: "Horsefly" },
    { ko: "각다귀", en: "Crane fly" },
    { ko: "깍지벌레", en: "Scale insect" },
    { ko: "노린재", en: "Stink bug" },
    { ko: "송장벌레", en: "Carrion beetle" },
    { ko: "집게벌레", en: "Earwig" },
    { ko: "톡토기", en: "Springtail" },
  ],
};

export const isLiarCategoryId = (value: unknown): value is LiarCategoryId =>
  typeof value === "string" && (LIAR_CATEGORY_IDS as string[]).includes(value);

// Max liars scales with the room: 1 by default, +1 per full block of 5 players.
// 3-4 -> 1, 5-9 -> 2, 10-14 -> 3, 15-19 -> 4 ...
export const maxLiarsFor = (playerCount: number): number =>
  Math.max(1, Math.floor(playerCount / 5) + 1);
